FROM golang:1.16

ENV TZ=Europe/Istanbul
#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV config=docker

WORKDIR /app

COPY ./ /app

RUN go mod download

EXPOSE 5000

ENTRYPOINT CompileDaemon --build="go build cmd/api/main.go" --command=./main